---
title: "English Reading Club"
baseURL: "https://english-reading-club.github.io/"
theme: "zen"
languageCode: "en-GB"
enableGitInfo: true
defaultContentLanguage: "en"
pluralizelisttitles: false
removePathAccents: true
paginate: 10
paginatePath: "page"
rssLimit: 20
author:
  name: "Your Name"
  url: "https://example.org/somepage"
  avatar: "path/to/some-image.jpg"

outputFormats:
  SearchIndex:
    mediaType: "application/json"
    baseName: "searchindex"
    isPlainText: true
    notAlternative: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1
    endLevel: 3
    ordered: false

taxonomies:
  category: categories
  tag: tags

outputs:
  home: ["HTML","RSS", "JSON", "SearchIndex"]
  section: ["HTML","RSS", "JSON"]

params:
  # logo: false
  mainSections:
    - "news"
    - "notes"
  contact: "info@example.org"
  copyright: "This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)."
  description: "The zen theme for Hugo example site."
  dateformat: "2 January, 2006"
  favicon: "logo.png"
  feedlinks: true
  footer: "Powered by [Hugo](https://gohugo.io/), [fork of Zen theme](https://github.com/jizusun/hugo-theme-zen) and [ ![](https://github.com/english-reading-club/english-reading-club.github.io/actions/workflows/main.yml/badge.svg) ](https://github.com/english-reading-club/english-reading-club.github.io/actions/workflows/main.yml) "
  icon: "logo.png"
  image: "logo.png"
  imageMaxWidth: 400
  mobileMenu: true
  poweredby: false
  sidebar: true
  submitted: true
  relatedposts: true
